<?php

namespace AppBundle\Repository\MusicBox;

use AppBundle\Entity\MusicBox\Student;



use Doctrine\ORM\EntityRepository;
/**
 * StudentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudentRepository extends EntityRepository
{
    public function findAllStudentById()
    {
   /*
        $em = $this->getEntityManager();
        $repository = $em
            ->getRepository(Student::class);

// createQueryBuilder() automatically selects FROM AppBundle:Product
// and aliases it to "p"
        $query = $repository->createQueryBuilder('s')
            ->where('s.id = id')
            ->setParameter('id', '>=0')
            ->getQuery();

        $students = $query;
*/

        $students = $this->getEntityManager()
            ->getRepository(Student::class)
            ->findAll();

        $result = [];

        foreach ($students as $student)
        {
            $result[$student->getId()] = $student->toArray();
        }

        return $result;
    }

}
